---
driver:
  name: ec2
  aws_ssh_key_id: kitchen
  region: us-east-1
  availability_zone: b
  subnet_id: subnet-5480567e
  instance_type: t2.micro
  image_id: ami-bd3ba0aa
 # image_id: ami-fce3c696
  security_group_ids: ['sg-2695da5d']
  retryable_tries: 120

provisioner:
  name: chef_zero

transport:
  ssh_key: ~/.ssh/kitchen
  #username: ubuntu
platforms:
  #- name: ubuntu-14.04
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[git-on-win::default]
    attributes:
