name 'git-on-win'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures git-on-win'
long_description 'Installs/Configures git-on-win'
version '0.1.0'
